### ISSUE TITLE
edsr-baseline-lte-fast has the channel error

### ISSUE THREAD

**Issue by HenryKang1** [jaewon-lee-b/lte#10]
Error message. I do not have error with any other weight such as swin lte or liif etc. I only have error with this weight. 
I check that coord_ has only 3 channel.  Is it suppose to be 4 channel?

""
too many indices for tensor of dimension 3
  File "D:\02_ericsson\LET\lte_main_1\models\ltep.py", line 59, in query_rgb
    coord_[:, :, :, 0] += vx * rx + eps_shift
  File "D:\02_ericsson\LET\lte_main_1\test.py", line 24, in batched_predict
    pred = model.query_rgb(coord[:, ql: qr, :], cell[:, ql: qr, :])
  File "D:\02_ericsson\LET\lte_main_1\demo.py", line 46, in <module>
    pred = batched_predict(model, ((img - 0.5) / 0.5).cuda().unsqueeze(0),
IndexError: too many indices for tensor of dimension 3
""

**Comment by jaewon-lee-b** [comment]
The coord is four channels since we split the HW domain into H and W, respectively. By doing this, we do not have to query points sequentially, leading to faster runtime.
