### ISSUE TITLE
Visualization of Fourier space

### ISSUE THREAD

**Issue by dmhdmhdmh** [jaewon-lee-b/lte#11]
Hello, do you have the code of 16-tap discrete Fourier transform of GT images? I don't know how to generate the GT spectrum. Thank you very much!

**Comment by jaewon-lee-b** [comment]
im = np.array(Image.open(img_gt_path+n_format_gt).convert('RGB'))
RF_ = (RF) // 2
im = im[xx_gt-RF_:xx_gt+RF_, yy_gt-RF_:yy_gt+RF_, :]
ff_r = np.fft.fft2(im[:, :, 0])
ff_r = np.fft.fftshift(ff_r)
ff_g = np.fft.fft2(im[:, :, 1])
ff_g = np.fft.fftshift(ff_g)
ff_b = np.fft.fft2(im[:, :, 2])
ff_b = np.fft.fftshift(ff_b)

ff = 20np.log(np.abs(ff_r)) + 20np.log(np.abs(ff_g)) + 20*np.log(np.abs(ff_b))
plt.imshow((ff), cmap=cmap)
plt.xticks([])
plt.yticks([])

plt.tight_layout()
plt.show()

**Comment by jaewon-lee-b** [comment]
@dmhdmhdmh. Here, RF indicates the receptive field so it will be 16.
