### ISSUE TITLE
non-interger scale for swinir

### ISSUE THREAD

**Issue by alsgur0720** [jaewon-lee-b/lte#14]
Hi, I have a question and leave an issue.

How do I do non-integer SR on swinIr+lte?

Maybe swinIr+lte can't do non-integer SR?

**Comment by jaewon-lee-b** [comment]
SR methods within decoder supporting arbitrary scales, such as MetaSR, LIIF, and LTE, can perform non-integer SR even with SwinIR.

In that case, we have to use reflection padding. Please see the eval.py. Thanks a lot!

**Comment by JQJ001** [comment]
Hi, I also want to achieve the non-integer super-resolution, but I don't fine the 'eval.py'.
Looking forward to your reply.
Thanks.

**Comment by JQJ001** [comment]
Hi, I also want to achieve the non-integer super-resolution, but I don't find the 'eval.py'.
Looking forward to your reply.
Thanks.

**Comment by JQJ001** [comment]
> Hi, I also want to achieve the non-integer super-resolution, but I don't find the 'eval.py'. Looking forward to your reply. Thanks.

Maybe the ‘test.py'.

**Comment by jaewon-lee-b** [comment]
Hi @JQJ001 

You can use demo.py

**Comment by JQJ001** [comment]
> Hi @JQJ001
> 
> You can use demo.py

OK
Thank you.
