### ISSUE TITLE
config error?

### ISSUE THREAD

**Issue by yuanlinwang** [jaewon-lee-b/lte#18]
https://github.com/jaewon-lee-b/lte/blob/7ab786d495b6414fd008918e2946e265673e75f7/configs/train-div2k/train_swinir-liif.yaml#L38
https://github.com/jaewon-lee-b/lte/blob/7ab786d495b6414fd008918e2946e265673e75f7/configs/train-div2k/train_swinir-liif.yaml#L41
should be 
```
name:liif
encoder_spec:
      name: swinir
```

**Comment by jaewon-lee-b** [comment]
Yes Thank you very much!
