### ISSUE TITLE
"Killed" in training

### ISSUE THREAD

**Issue by LYX-ll** [jaewon-lee-b/lte#22]
Very good work!
Hello, I want to train but I get "Killed" and then the training is over. What is the reason for this?
The questions are as follows:
(lte) root@401240707274117120-taskrole1-0:/gemini/code/lte-main# python train.py --config configs/train-div2k/train_edsr-baseline-lte.yaml --gpu 0
config loaded.
Killed

**Comment by jaewon-lee-b** [comment]
Hello @LYX-ll 

In common, if the memory is limited, the process is killed
