### ISSUE TITLE
Question about validation process of SWIN-LTE

### ISSUE THREAD

**Issue by zzzack66** [jaewon-lee-b/lte#23]
Thanks for your awesome work. During the validation of SWIN-LTE, do we need to specify the window size of SWIN-IR encoder like the process of testing?

Here is the validation function,:
https://github.com/jaewon-lee-b/lte/blob/a8815d6ac8a643cd0463a092fa0f58e03935b343/train.py#L181
and in function eval_psnr, you specify the evaluation of SWIN encoder:
https://github.com/jaewon-lee-b/lte/blob/a8815d6ac8a643cd0463a092fa0f58e03935b343/test.py#L67

However, in the validation process, it didn't step into this line. Will it affect the result of validation?

**Comment by jaewon-lee-b** [comment]
Hi @zzzack66

That if expression is for the other encoders, such as EDSR-baseline or RDN.

**Comment by zzzack66** [comment]
Thanks for your reply.
As I understand the code, the validation phase of swin-lte also goes into that line. Should we set the window-size during the val phase?
I understand that when we are training swin-lte we set the window size to 8 by default.
I'm looking forward to your reply.

**Comment by jaewon-lee-b** [comment]
Yes, we have to specify the window size. The example is given in the readme.

**Comment by zzzack66** [comment]
As far as I understand the code, the validation config file of swin-lte needs to be modified. I think the validation result of swin-lte might be inaccurate. I will try to make some changes next. I will let you know the result after the experiment.
Thanks for your reply!
