### ISSUE TITLE
Paper PDF too large

### ISSUE THREAD

**Issue by Yuxiang1995** [jaewon-lee-b/lte#4]
Hi, I'm be interested in your work. But why your paper pdf so large? Its too hard to download = =
https://pdf.cdn.readpaper.com/arxivPdf/2111.08918_v4.pdf

**Comment by jaewon-lee-b** [comment]
Hi @Yuxiang1995,

That version is my mistake (latex package issue for cvpr camera-ready version - \usepackage[accsupp]{axessibility})

Please use the following link.
IPL Server - https://ipl.dgist.ac.kr/LTE_cvpr.pdf
CVPR Proceedings - https://openaccess.thecvf.com/content/CVPR2022/papers/Lee_Local_Texture_Estimator_for_Implicit_Representation_Function_CVPR_2022_paper.pdf
