### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by marsmarks** [jaewon-lee-b/lte#6]
When I run the code of step 2: repeat experiments, the following errors occur. How can I solve them
FileNotFoundError: [Errno 2] No such file or directory: './load/div2k/DIV2K_valid_LR_bicubic/X2'

**Comment by jaewon-lee-b** [comment]
Hi @marsmarks 
Download DIV2K dataset from https://data.vision.ee.ethz.ch/cvl/DIV2K/

Then, put them to ./load/div2k/
