### ISSUE TITLE
Can you tell me how to show the low or high frequency information as the fig.7,especially the second row information ?

### ISSUE THREAD

**Issue by GZHU-DVL** [jaewon-lee-b/lte#9]

**Comment by jaewon-lee-b** [comment]
Hello @GZHU-DVL.  

Patchify the image into 2^N x 2^N (we use 16x16)

Then, run the abs(FFT(x)) to get the intensity. Here, the farthest points indicate the highest frequency bin. Thank you.

**Comment by jaewon-lee-b** [comment]
Using a patch with various patterns may result in uninterpretable intensity diagram.

We recommend the image with a single pattern as in Fig7.

**Comment by jaewon-lee-b** [comment]
im = np.array(Image.open(img_gt_path+n_format_gt).convert('RGB'))
RF_ = (RF) // 2
im = im[xx_gt-RF_:xx_gt+RF_, yy_gt-RF_:yy_gt+RF_, :]
ff_r = np.fft.fft2(im[:, :, 0])
ff_r = np.fft.fftshift(ff_r)
ff_g = np.fft.fft2(im[:, :, 1])
ff_g = np.fft.fftshift(ff_g)
ff_b = np.fft.fft2(im[:, :, 2])
ff_b = np.fft.fftshift(ff_b)

ff = 20*np.log(np.abs(ff_r)) + 20*np.log(np.abs(ff_g)) + 20*np.log(np.abs(ff_b))
plt.imshow((ff), cmap=cmap)
plt.xticks([])
plt.yticks([])

plt.tight_layout()
plt.show()
